# -*- mode: ruby -*-
# vi: set ft=ruby :

require 'fileutils'

Vagrant.require_version ">= 2.0.0"
$inventory = File.path($inventory, File.dirname(__FILE__))


# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|

    config.vm.provision :shell, <<-SHELL
      yum install openssh-server
    SHELL
  
    # Every Vagrant development environment requires a box. You can search for
    # boxes at https://atlas.hashicorp.com/search.
    config.vm.box = "centos/7"
    config.vm.box_check_update = false
  
    config.vm.define "master1" do |node|
      node.name = "master1"
      node.vm.network "private_network", ip: "192.168.200.10"
      node.vm.provider "hyperv" do |h|
        h.cpus = 1
        h.memory=512
        h.vm_integration_services = {
          guest_service_interface: true,
          CustomVMSRV: true
        }
      end

    end

  end