# -*- mode: ruby -*-
# vi: set ft=ruby :

# 下载镜像
# vagrant box add centos/7 http://aiziyuer.synology.me:10080/cloud.centos.org/centos/7/vagrant/x86_64/CentOS-7-x86_64-Vagrant-1905_01.HyperV.box
# 启动镜像
# vagrant up

boxes = [
  {
      :name => "master1",
      :eth0 => "192.168.200.10",
      :mem => "512",
      :cpu => "1"
  },
  # {
  #     :name => "slave1",
  #     :eth1 => "192.168.205.11",
  #     :mem => "1024",
  #     :cpu => "1"
  # },
  # {
  #     :name => "slave2",
  #     :eth1 => "192.168.205.12",
  #     :mem => "1024",
  #     :cpu => "1"
  # }
]

Vagrant.configure("2") do |config|
  
    config.vm.box = "centos/7"

    # 循环设置每台虚拟机
    boxes.each do |opts|
      config.vm.define opts[:name] do |config|
        config.vm.hostname = opts[:name]

        # 配置内存和CPU
        config.vm.provider "hyperv" do |h|
          h.cpus=opts[:cpu]
          h.memory=opts[:mem]
        end

        # 配置 IP
        config.vm.network :private_network, ip: opts[:eth0]


      end
    end

  end